name: Build and publish a 🛢️ container
description: 'GHA to build and publish a 🛢️ container'

inputs:
  build_arch:
    description: What arch to build for. Comma seperated list.
    default: linux/amd64
  build_args:
    description: Build args to pass to the build. This is a string of key=value pairs seperated by a newline.
  build_context:
    description: What context to use for the build. Defaults to the current directory.
    default: .
  buildfile:
    description: What Container/Dockerfile to use for the build. Defaults to Dockerfile.
    default: Dockerfile
  publish:
    description: Whether to publish the container or not.
    default: 'true'
  registry:
    description: The registry to publish to.
    default: ghcr.io
  registry_username:
    description: The username to use for the registry.
    default: ${{ github.repository_owner }}
  registry_password:
    description: The password to use for the registry.
    required: true
  docker_username:
    description: The username to use for the docker registry.
  docker_password:
    description: The password to use for the docker registry.
  tags:
    description: The tags to use for the container. This is a string of tags seperated by a newline.

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # needed for multi-arch builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # needed for multi-arch builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the container registry
      uses: docker/login-action@v3
      if: ${{ inputs.publish == 'true' }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Log in to the Docker container registry
      uses: docker/login-action@v3
      if: ${{ inputs.publish == 'true' && inputs.docker_username != '' && inputs.docker_password != '' }}
      with:
        registry: docker.io
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Get the tags
      shell: bash
      if: ${{ inputs.publish == 'true' && inputs.tags == '' }}
      run: ${{ github.action_path }}/get_the_tags.py --repo "${{ github.repository }}" --ref "${{ github.ref_name }}" --log DEBUG
      id: tags

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.build_context }}
        # see https://github.com/docker/build-push-action/issues/820
        provenance: false
        platforms: ${{ inputs.build_arch }}
        push: ${{ inputs.publish == 'true' }}
        # if publish is false, tag as test, otherwise use the tags from the previous step
        tags: ${{ inputs.publish == 'true' && steps.tags.outputs.tags || inputs.tags }}
        file: ${{ inputs.buildfile }}
        build-args: ${{ inputs.build_args }}
