name: Build and publish a 🛢️ container
description: 'GHA to build and publish a 🛢️ container'

inputs:
  build_arch:
    description: What arch to build for. Comma seperated list
    default: linux/amd64
  buildfile:
    description: What Container/Dockerfile to use for the build. Defaults to Dockerfile.
    default: Dockerfile
  github_token:
    description: The Github Auth Token
    required: true
  publish:
    description: Whether to publish the container or not
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # needed for multi-arch builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # needed for multi-arch builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      if: ${{ inputs.publish == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Get the tags
      shell: bash
      if: ${{ inputs.publish == 'true' }}
      run: ${{ github.action_path }}/get_the_tags.py --repo "${{ github.repository }}" --ref "${{ github.ref_name }}" --log DEBUG
      id: tags

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        # see https://github.com/docker/build-push-action/issues/820
        provenance: false
        platforms: ${{ inputs.build_arch }}
        push: ${{ inputs.publish == 'true' }}
        # if publish is false, tag as test, otherwise use the tags from the previous step
        tags: ${{ inputs.publish == 'true' && steps.tags.outputs.tags || 'ci/test:dummy' }}
        file: ${{ inputs.buildfile }}
